---
- name: Ensure images directory exists
  file:
    state: directory
    dest: "{{ stack_user_home }}/images"
    mode: 0755

- name: Synchronize utility scripts to stack user home directory
  synchronize:
    src: "{{ role_path }}/files/scripts/"
    dest: "{{ stack_user_home}}/scripts/"
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    archive: true
    recursive: true
    rsync_opts:
      - "--chmod=F755"

- name: Copy overcloud_deploy script to stack user home directorry
  template:
    src: overcloud_deploy.j2
    dest: "{{ stack_user_home}}/scripts/overcloud_deploy.sh"
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
