---
- name: Synchronize user-files to stack user home directory
  synchronize:
    src: "{{ role_path }}/files/user-files/"
    dest: "{{ stack_user_files }}"
    archive: true
    recursive: true
    rsync_opts:
      - "--chmod=F755"

- name: Synchronize utility scripts to stack user home directory
  synchronize:
    src: "{{ role_path }}/files/scripts/"
    dest: "{{ stack_user_home }}/scripts/"
    archive: true
    recursive: true
    rsync_opts:
      - "--chmod=F755"
