---

# Check to see if this if the user has already created an instackenv.json file
- name: See if instackenv.json exists
  stat:
    path: "{{ stack_user_files }}/instackenv.json"
  register: instackenv_json


- name: Run import and provsion
  shell: >
    source {{ stack_user_home }}/stackrc;
    {{ scripts_path }}/import_and_provision.sh
  when: instackenv_json.stat.exists|bool

- name: Copy installed overcloud heat templates to stack user home directory
  synchronize:
    src: "{{ overcloud_templates_dir }}/"
    dest: "{{ stack_user_home }}/templates/"
    mode: pull
    archive: true
    recursive: true
  delegate_to: "{{ inventory_hostname }}"
  become: true
  become_user: root

- name: Set overcloud heat templates directory permissions
  file:
    path: "{{ stack_user_home }}/templates/"
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    recurse: true
  become: true
  become_user: root

- name: Copy Ceph wipe disk files to stack user home directory
  synchronize:
    src: "{{ role_path }}/files/ceph-overcloud-files/"
    dest: "{{ stack_user_home }}/ceph-overcloud-files/"
    archive: true
    recursive: true
    rsync_opts:
      - "--chmod=F755"

- name: Synchronize user-templates to stack user home directory
  synchronize:
    src: "{{ role_path }}/files/user-templates/"
    dest: "{{ stack_user_templates }}"
    archive: true
    recursive: true
    rsync_opts:
      - "--chmod=F755"

- name: Get list of user templates for deploy script
  find:
    path: "{{ stack_user_templates }}"
    patterns: "*.yaml, *.yml"
  register: user_templates

- name: Copy overcloud_deploy script to stack user home directory
  template:
    src: overcloud_deploy.j2
    dest: "{{ stack_user_home}}/scripts/overcloud_deploy.sh"
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755

- name: See if overcloudrc exists
  stat:
    path: "{{ stackrc_path }}"
  register: stackrc

- name: Check to see if the overcloud is already provisioned
  shell: >
    source {{ stackrc_path }};
    {{ scripts_path }}/check_services.py -s orchestration
  register: overcloud
  when: stackrc.stat.exists

- name: Copy overcloud_deploy script to stack user home directory
  template:
    src: overcloud_deploy.j2
    dest: "{{ stack_user_home}}/scripts/overcloud_deploy.sh"
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
