---

- name: Set hostname
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }} {{ undercloud_conf.undercloud_hostname }}"
    line: >
      {{ ansible_default_ipv4.address }}
      {{ undercloud_conf.undercloud_hostname }} {{ undercloud_conf.undercloud_shortname }}
  when: undercloud_conf.undercloud_hostname is defined and undercloud_conf.undercloud_shortname is defined


- name: Setup latest delorean repos
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.dest }}'
    mode: 0440
  with_items:
    - { url: "https://trunk.rdoproject.org/centos7-{{ stack_release }}/current/delorean.repo",
        dest: "/etc/yum.repos.d/delorean-{{ stack_release }}.repo" }
    - { url: "http://trunk.rdoproject.org/centos7-{{ stack_release }}/delorean-deps.repo",
        dest: "/etc/yum.repos.d/delorean-deps-{{ stack_release }}.repo" }
    - { url: "http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master-tripleo/delorean.repo",
        dest: "/etc/yum.repos.d/delorean.repo" }

- name: Setup ceph
  yum:
    name: "{{ ceph_yum_package }}"
    enablerepo: extras
    disable_gpg_check: true
    state: present

- name: Install needed packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - python-tripleoclient
    - tmux
    - vim
    - yum-plugin-priorities

- name: Setup undercloud.conf
  template:
    dest: "{{ stack_user_home }}/undercloud.conf"
    src: undercloud.conf
    mode: 0440
    owner: '{{ stack_user }}'
    group: '{{ stack_user }}'
