---
- name: See if stackrc exists
  stat:
    path: "{{ stackrc_path }}"
  register: stackrc

- name: Install the undercloud
  command: openstack undercloud install
  args:
    chdir: "{{ stack_user_home }}"
  when: not stackrc.stat.exists|bool

- name: Set bashrc to source stackrc file if it exists
  lineinfile:
    dest: "{{ stack_user_home }}/.bashrc"
    regexp: "^source {{ stackrc_path }}"
    line: "source {{ stackrc_path }}"
  when: stackrc.stat.exists

- name: Ensure images directory exists
  file:
    state: directory
    dest: "{{ stack_user_home }}/images"
    mode: 0755
  when: stackrc.stat.exists|bool

- name: Build overcloud images
  command: openstack overcloud image build --all
  args:
    chdir: "{{ stack_user_home }}/images"
  environment:
    DIB_YUM_REPO_CONF: "/etc/yum.repos.d/delorean*"
  when: stackrc.stat.exists|bool

- name: Upload overcloud images
  shell: >
    openstack overcloud image upload --image-path "{{ stack_user_home }}/images"
  args:
    chdir: "{{ stack_user_home }}"
  when: stackrc.stat.exists|bool
